### ISSUE TITLE
Summoner module sometimes ignores custom messages

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#203]
As evidenced in the following config:

```
{
    "core": {
        "username": "codinghorrorbot",
        "password": "OMGpasswordHACKSAUR"
    },
    "plugins": {
        "summoner": {
            "cooldown": 60000,
            "messages": [
                "@%username% Is Doing It Wrong™"
            ]
        }
    }
}
```

The message was the default instead of the custom one.

**Comment by RaceProUK** [comment]
This config does it too:

```
---
core:
  username: NetBot
  password: lalalalaicanthearyoulalalala
  owner: RaceProUK
plugins:
  summoner:
    - "Long time no see, @%username%. My loathsome copy."
    - "@%username%, I was created for the sole purpose of destroying you, but I can never seem to defeat you. That is why @RaceProUK rebuilt my own body with her own paws."
    - "See me as I am, no longer afraid of anything."
    - "Face me if you wish to have the Chaos Emerald!"
    - "I will battle you as many times as necessary!"
```
